version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    ports:
      - "8000:8000"
    volumes:
      - "./data:/home/dynamodblocal/data"

  dynamodb-init:
    image: amazon/aws-cli:latest
    container_name: dynamodb-init
    depends_on:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    command: >
      sh -c "
      sleep 5 &&
      aws dynamodb create-table \
        --table-name todos \
        --attribute-definitions AttributeName=id,AttributeType=S \
        --key-schema AttributeName=id,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST \
        --endpoint-url http://dynamodb-local:8000 \
        --region eu-central-1 &&
      aws dynamodb create-table \
        --table-name users \
        --attribute-definitions AttributeName=id,AttributeType=S \
        --key-schema AttributeName=id,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST \
        --endpoint-url http://dynamodb-local:8000 \
        --region eu-central-1
      "

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,dynamodb
      - DEFAULT_REGION=eu-central-1
    volumes:
      - "./localstack:/var/lib/localstack"

  backend:
    build: .
    container_name: taskflow-backend
    depends_on:
      - dynamodb-local
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    command: ["java", "-jar", "/app/app.jar"]