spring:
  application:
    name: taskflow-backend
  
  # Allow circular references for local development
  main:
    allow-circular-references: true
  
  # Disable Docker Compose for local development
  docker:
    compose:
      enabled: false

# Server Configuration
server:
  port: ${SERVER_PORT:8081}

# Database Configuration
spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

# DynamoDB Configuration
dynamodb:
  enabled: ${DYNAMODB_ENABLED:false}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-default-secret}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

# Rate Limiting
rate:
  limit:
    auth:
      requests-per-minute: ${RATE_LIMIT_AUTH_REQUESTS_PER_MINUTE:5}
      refresh-requests-per-minute: ${RATE_LIMIT_REFRESH_REQUESTS_PER_MINUTE:10} 