spring:
  application:
    name: taskflow-backend
  
  # Allow circular references for local development
  main:
    allow-circular-references: true
  
  # H2 in-memory database for local smoke testing
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

# Disable DynamoDB for local testing
dynamodb:
  enabled: false

jwt:
  secret: ${JWT_SECRET:your-default-secret}
  expiration-ms: 86400000

rate:
  limit:
    auth:
      requests-per-minute: 5
      refresh-requests-per-minute: 10 