spring:
  application:
    name: taskflow-backend

  # AWS region set to eu-central-1 to match the DynamoDB Local and LocalStack configs
  cloud:
    aws:
      region:
        static: eu-central-1
      credentials:
        access-key: dummy   # DynamoDB Local ignores actual values
        secret-key: dummy
      endpoint: http://localhost:8000

dynamodb:
  table:
    name: todos

aws:
  dynamodb:
    endpoint: http://localhost:8000  # DynamoDB Local endpoint (fallback)

jwt:
  secret: ${JWT_SECRET:your-default-secret}
  expiration-ms: 86400000

rate:
  limit:
    auth:
      requests-per-minute: 5
      refresh-requests-per-minute: 10

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:8080
    - http://localhost:4200
    - http://127.0.0.1:3000
    - http://127.0.0.1:3001
    - http://127.0.0.1:8080
    - http://127.0.0.1:4200
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
    - HEAD
  allowed-headers:
    - Authorization
    - Content-Type
    - Accept
    - Origin
    - X-Requested-With
    - Cache-Control
    - Pragma
    - X-CSRF-TOKEN
    - X-API-Key
    - X-Client-Version
  exposed-headers:
    - Authorization
    - X-Total-Count
    - X-Page-Count
    - X-Current-Page
    - X-Rate-Limit-Remaining
    - X-Rate-Limit-Reset
  allow-credentials: true
  max-age: 3600