spring:
  application:
    name: taskflow-backend

  # AWS region set to eu-central-1 to match the DynamoDB Local and LocalStack configs
  cloud:
    aws:
      region:
        static: eu-central-1
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      endpoint: ${AWS_DYNAMODB_ENDPOINT:}

dynamodb:
  table:
    name: todos
  enabled: true

aws:
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000

rate:
  limit:
    auth:
      requests-per-minute: 5
      refresh-requests-per-minute: 10

# CORS Configuration for Production
# Update these with your actual production domains
cors:
  allowed-origins:
    - https://yourdomain.com
    - https://www.yourdomain.com
    - https://app.yourdomain.com
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
    - HEAD
  allowed-headers:
    - Authorization
    - Content-Type
    - Accept
    - Origin
    - X-Requested-With
    - Cache-Control
    - Pragma
    - X-CSRF-TOKEN
    - X-API-Key
    - X-Client-Version
  exposed-headers:
    - Authorization
    - X-Total-Count
    - X-Page-Count
    - X-Current-Page
    - X-Rate-Limit-Remaining
    - X-Rate-Limit-Reset
  allow-credentials: true
  max-age: 3600 